---
encrypt_kms.settings:
  type: config_object
  label: 'Encrypt KMS Settings'
  mapping:
    aws_key:
      type: string
      label: 'AWS Key ID'
    aws_secret:
      type: string
      label: 'AWS Secret'
    aws_region:
      type: string
      label: 'AWS Region'
